<?php


//~ Template for add-edit-meal.php
// variables:
//  $errors - validation errors
//  $meal - submitted Meal
//  $edit - true for EDIT, false for ADD

function error_field($title, array $errors) {
    foreach ($errors as $error) {
        /* @var $error RError */
        if ($error->getSource() == $title) {
            return ' error-field';
        }
    }
    return '';
}

/* @var $meal Meal */
?>

<h1>
    <?php if ($edit): ?>
        <?php 
        echo "Edit Meal: " . Utils::escape( $meal->getTeamLead() );
        ?>
    <?php else: ?>
        Add new Meal
    <?php endif; ?>
</h1>

<?php if (!empty($errors)): ?>
<ul class="errors">
    <?php foreach ($errors as $error): ?>
        <?php /* @var $error RError */ ?>
        <li><?php echo $error->getMessage(); ?></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>

<form action="#" method="post">
    <fieldset>
        <div class='field'>
            <label>Meal Team</label>
            <select name="meal[meal_team_id]">
                <?php
                    foreach( Utils::getMealTeams() as $mt_info ) {
                        echo '<option value="';
                        echo $mt_info->getId() . '" ';
                        if ( $edit && $mt_info->getId() == $meal->getMealTeamId()) {
                            echo 'selected="selected"';
                        }
                        $lead_names = $mt_info->getLead1Name();
                        if ( $mt_info->getLead2Name() ) {
                            $lead_names .= ', ' . $mt_info->getLead2Name();
                        }
                        echo "'>" . $lead_names . "</option>";
                    }
                ?>
            </select>
        </div>

        <div  class="field">
            <label>Summary:</label>
            <input type="text" name="meal[summary]" value="<?php echo Utils::escape($meal->getSummary()); ?>"
                   class="text<?php echo error_field('summary', $errors); ?>"/>
        </div>
        <div  class="field">
            <label>Details:</label>
            <textarea name="meal[details]" rows="4" cols="40"
                      class="text<?php echo error_field('details', $errors); ?>"/>
                <?php echo Utils::escape($meal->getDetails()); ?>
            </textarea>
        </div>
        <div class="field">
            <label>Meal Cost:</label>
            $<input type="number" name="meal[meal_cost]" step="0.10" placeholder="0.00"
                value='<?php echo $meal ? $meal->getMealCost() : "0.00"; ?>'/>
        </div>
        <div class="field">
            <label>Meal Cost (0 - 5):</label>
            $<input type="number" name="meal[meal_cost_1]" step="0.10" placeholder="0.00"
                value='<?php echo $meal ? $meal->getMealCost1() : "0.00"; ?>'/>
        </div>
        <div class="field">
            <label>Meal Cost (6-12):</label>
            $<input type="number" name="meal[meal_cost_2]" step="0.10" placeholder="0.00"
                value='<?php echo $meal ? $meal->getMealCost2() : "0.00"; ?>'/>
        </div>
        <div class="field">
            <label>Meal Date:</label>
            <input type="date" name="meal[meal_date]" 
               value='<?php echo $meal_date_string; ?>'/> 
        </div>
        <div class="field">
            <label>Meal Time:</label>
            <input type="time" name="meal[meal_time]" 
               value='<?php echo $meal_time_string; ?>'/> 
        </div>
        <div class="field">
            <label>Signup Deadline Date:</label>
            <input type="date" name="meal[deadline_date]" 
               value='<?php echo $deadline_date_string; ?>'/> 
        </div>
        <div class="field">
            <label>Signup Deadline Time:</label>
            <input type="time" name="meal[deadline_time]" 
               value='<?php echo $deadline_time_string; ?>'/> 
        </div>
        <div  class="field">
            <label>Tags:</label>
            <input type="text" name="meal[tags]" value="<?php echo Utils::escape($meal->getTags()); ?>"
                   class="text<?php echo error_field('tags', $errors); ?>"/>
        </div>
        <div  class="field">
            <label>Sign Up Limit:</label>
            <input type="number" step="1" min="0" name="meal[sign_up_limit]" value="<?php echo Utils::escape($meal->getSignUpLimit()); ?>"
                   class="text<?php echo error_field('sign_up_limit', $errors); ?>"/>
        </div>
        <div class="wrapper">
            <input type="submit" name="cancel" value="CANCEL" class="submit" />
            <input type="submit" name="save" value="<?php echo $edit ? 'SAVE' : 'ADD'; ?>" class="submit" />
        </div>
    </fieldset>
</form>

<p>
    <?php $backLink = Utils::createLink('meal-list', array()); ?>
    <a href="<?php echo $backLink; ?>"><img src="img/action/back.png" alt="" title="Back to the list." class="icon"/></a>&nbsp;
    <a href="<?php echo $backLink; ?>">To the list</a>
</p>

