<?php


//~ Template for meal-signup.php
// variables:
//  $errors - validation errors
//  $meal - Meal for which to add or remove persons

function error_field($title, array $errors) {
    foreach ($errors as $error) {
        /* @var $error Error */
        if ($error->getSource() == $title) {
            return ' error-field';
        }
    }
    return '';
}

function show_member_attendees( $member_attendees, $unit_member_ids ) {
    $role = Utils::getUserRole();
    foreach( $member_attendees as $attendee ) {
        $person = $attendee->getPerson();
        $remove_ids = 'remove_ids[]';
        $edit_veg = 'edit_veg[]';
        $edit_gf = 'edit_gf[]';
        $edit_df = 'edit_df[]';
        echo "<tr>";
        echo "<td>";
        echo "<input type='checkbox' name='" . $remove_ids . "'";
        if ( $role == Utils::USER ) {
            if ( ! in_array( $person->getId(), 
                             $unit_member_ids )) {
                echo " disabled";
            }
        }
        echo " value='" . $person->getId() . "'>&nbsp;";
        echo $person->getFirstName() . " " .
             $person->getLastName() . " [" .
             $person->getUnit() . $person->getSubUnit() . "]"; 
             echo "</input>";
        echo "</td><td>";
        echo "<input type='checkbox' name='" . $edit_veg . "'";
        if ( $attendee->getSpecialsVeg() ) {
            echo " checked";
        }
        if ( $role == Utils::USER ) {
            if ( ! in_array( $person->getId(), 
                             $unit_member_ids )) {
                echo " disabled";
            }
        }
        echo " value='" . $person->getId() . "'>&nbsp;";
        echo "</input>";
        echo "</td><td>";
        echo "<input type='checkbox' name='" . $edit_gf . "'";
        if ( $attendee->getSpecialsGF() ) {
            echo " checked";
        }
        if ( $role == Utils::USER ) {
            if ( ! in_array( $person->getId(), 
                             $unit_member_ids )) {
                echo " disabled";
            }
        }
        echo " value='" . $person->getId() . "'>&nbsp;";
        echo "</input>";
        echo "</td><td>";
        echo "<input type='checkbox' name='" . $edit_df . "'";
        if ( $attendee->getSpecialsDF() ) {
            echo " checked";
        }
        if ( $role == Utils::USER ) {
            if ( ! in_array( $person->getId(), 
                             $unit_member_ids )) {
                echo " disabled";
            }
        }
        echo " value='" . $person->getId() . "'>&nbsp;";
        echo "</input>";
        /*
        echo "</td><td>";
        echo "<input type='text' size='15' name='edit_other-" . $person->getId() . "'";
        if ( $role == Utils::USER ) {
            if ( ! in_array( $person->getId(), 
                             $unit_member_ids )) {
                echo " disabled";
            }
        }
        if ( $attendee->getSpecialsOther() != '' ) {
            echo " value='" . $attendee->getSpecialsOther() . "' ";
        }
        echo "></input>";
        */
        echo "</td>";
        if ( $role == Utils::MEALS_ADMIN ) {
            echo "<td>";
            echo "$<input type='number' step='.10' name='extra_cost-" . $person->getId() . "'";
            if ( $attendee->getExtraCost() != '' ) {
                echo " value='" . number_format( $attendee->getExtraCost(), 2 ) . "' ";
            }
            echo "></input>";
            echo "</td>";
        }
        echo "</td></tr>";
    }   
}

function show_guests( $guests, $guest_unit_id ) {
    $role = Utils::getUserRole();
    foreach( $guests as $guest ) {
        $remove_guest_ids = 'remove_guest_ids[]';
        $edit_veg = 'guest_edit_veg[]';
        $edit_gf = 'guest_edit_gf[]';
        $edit_df = 'guest_edit_df[]';
        echo "<tr>";
        echo "<td>";
        echo "<input type='checkbox' name='" . $remove_guest_ids . "'";
        if ( $role == Utils::USER ) {
            if ( $guest->getUnitId() != $guest_unit_id ) {
                echo " disabled";
            }
        }
        echo " value='" . $guest->getId() . "'>&nbsp;";
        echo "Unit " . $guest->getUnitId() . " guest - " .
             $guest->getAgeGroup();
        echo "</input>";
        echo "</td><td>";
        echo "<input type='checkbox' name='" . $edit_veg . "'";
        if ( $guest->getSpecialsVeg() ) {
            echo " checked";
        }
        if ( $role == Utils::USER ) {
            if ( $guest->getUnitId() != $guest_unit_id ) {
                echo " disabled";
            }
        }
        echo " value='" . $guest->getId() . "'>&nbsp;";
        echo "</input>";
        echo "</td><td>";
        echo "<input type='checkbox' name='" . $edit_gf . "'";
        if ( $guest->getSpecialsGF() ) {
            echo " checked";
        }
        if ( $role == Utils::USER ) {
            if ( $guest->getUnitId() != $guest_unit_id ) {
                echo " disabled";
            }
        }
        echo " value='" . $guest->getId() . "'>&nbsp;";
        echo "</input>";
        echo "</td><td>";
        echo "<input type='checkbox' name='" . $edit_df . "'";
        if ( $guest->getSpecialsDF() ) {
            echo " checked";
        }
        if ( $role == Utils::USER ) {
            if ( $guest->getUnitId() != $guest_unit_id ) {
                echo " disabled";
            }
        }
        echo " value='" . $guest->getId() . "'>&nbsp;";
        echo "</input>";
        /*
        echo "</td><td>";
        echo "<input type='text' size='15' name='guest_edit_other-" . $guest->getId() . "'";
        if ( $role == Utils::USER ) {
            if ( $guest->getUnitId() != $guest_unit_id ) {
                echo " disabled";
            }
        }
        if ( $guest->getSpecialsOther() != '' ) {
            echo " value='" . $guest->getSpecialsOther() . "' ";
        }
        echo "></input>";
        */
        echo "</td>";
        if ( $role == Utils::MEALS_ADMIN ) {
            echo "<td>";
            echo "$<input type='number' step='.10' name='guest_extra_cost-" . $guest->getId() . "'";
            if ( $guest->getExtraCost() != '' ) {
                echo " value='" . number_format( $guest->getExtraCost(), 2 ) . "' ";
            }
            echo "></input>";
            echo "</td>";
        }
        echo "</td></tr>";
    }   
}
?>

<?php if (!empty($errors)): ?>
<ul class="errors">
    <?php foreach ($errors as $error): ?>
        <?php /* @var $error Error */ ?>
        <li><?php echo $error->getMessage(); ?></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>

<div class="aligncenter">
    <h3>
        <?php echo 'Meal: ' . $meal->getSummary() .' - Team: ' 
            . Utils::getMealTeamLeads( $meal->getMealTeamId() ); ?>
    </h3>
    <p>Date and Time:  <?php echo $meal->getDateTimeMDY(); ?></p>
    <p>Signup by:  <?php echo $meal->getDeadlineMDY(); ?></p>
    <p>Cost: $<?php echo $meal->getMealCost(); ?>, 
    <p>Young child: $<?php echo $meal->getMealCost1(); ?>, 
    <p>Older child: $<?php echo $meal->getMealCost2(); ?></p> 
</div>
<br/>
<form action="#" method="post">
    <fieldset>
        <div  class="field">
            <label>Add:</label>
            <select class="signup_list" name="add_attendees[]" multiple size=4 >
            <?php foreach ( $unit_members as $unit_person ) {
                if ( ! in_array( $unit_person->getPersonId(), 
                                 $member_attendee_ids )) {
                    echo '<option value = ' . 
                         $unit_person->getPersonId() . '> ' .
                         $unit_person->getFirstName() . ' ' . 
                         $unit_person->getLastName() . ' [' .
                         $unit_person->getUnitId() . $unit_person->getSubUnit() . ']' .
                         '</option>';
                }
            } ?>
            </select>
            <input type='submit' name='add_member' value='Add'>
        </div>
        <div class="field">
            <label>Guests:</label>
            <fieldset>
                <?php if ( $role == Utils::MEALS_ADMIN ): ?>
                    <div class="field">
                        <label>Unit:</label>
                        <input name='guest_unit' size="5" value=
                            <?php 
                                echo $unit_id_plus['unit_id'] . $unit_id_plus['sub_unit']; 
                            ?> >
                    </div>
                <?php endif; ?>
                <div class="field">
                    <label>Adults:</label>
                    <input name='guest_adults' type='number' step='1' min='0' value='0'>
                </div>
                <div class="field">
                    <label>Child (<8):</label>
                    <input name='guest_child_young' type='number' step='1' min='0' value='0'>
                    <input type='submit' name='add_guest' value='Add'>
                </div>
                <div class="field">
                    <label>Child (8-11):</label>
                    <input name='guest_child_older' type='number' step='1' min='0' value='0'>
                </div>
                <!-- <input type="hidden" name="guest_child_cost" value="0" > -->
            </fieldset>
        </div>
        <div class="field">
            <label>Attending:</label>
            <table id="attendee_table">
              <col class="attendee_name_col">
              <col class="attendee_special_col">
              <col class="attendee_special_col">
              <col class="attendee_special_col">
              <!-- <col class="attendee_allergy_col"> -->
              <?php
                if ( $role == Utils::MEALS_ADMIN ) {
                    echo '<col class="attendee_extra_col">';
                }
              ?>
              <tr>
                <th>Person</th>
                <th>Veg.</th>
                <th>GF</th>
                <th>DF</th>
                <!-- <th>Allergies</th> -->
                <?php
                    if ( $role == Utils::MEALS_ADMIN ) {
                        echo '<th>Extra Cost</th>';
                    }
                ?>
              </tr>
            
            <?php 
                if ( $member_attendees ) {
                    show_member_attendees( $member_attendees, $unit_member_ids );
                }
                if ( $guests ) {
                    show_guests( $guests, 
                                 $unit_id_plus['unit_id'] . $unit_id_plus['sub_unit'] );
                }
            ?> 
            <tr>
              <td span=4>
                <input type = 'submit' name = 'remove' value = 'Remove'>
              </td>
              <td>
                <input type = 'submit' name = 'edit' value = 'Save'>
              </td>
            </tr>
            <tr><td>&nbsp;</td></tr>
        </table>
        </div>
    </fieldset>
</form>
<div class="field">
    <label>Totals:</label>
    <table class="detail">
      <col class="summary_col">
      <col class="summary_col">
      <col class="summary_col">
      <col class="summary_col">
      <col class="summary_col">
      <col class="summary_col">
      <?php 
          if ( $role == Utils::MEALS_ADMIN ) {
              echo '<col id="summary_income_col">';
          }
      ?>
      <tr>
        <th colspan="3">Attending</th>
        <th>Veg.</th>
        <th>GF</th>
        <th>DF</th>
      <?php 
          if ( $role == Utils::MEALS_ADMIN ) {
              echo "<th>Income</th>";
          }
      ?>
      </tr>
      <tr>
        <th>Adult</th>
        <th colspan="2">Child</th>
        <th/>
        <th/>
        <th/>
      </tr>
        <th/>
        <th>Young</th>
        <th>Older</th>
        <th/>
        <th/>
        <th/>
      </tr>
      <tr>
      <tr>
        <td class="summary_cell"><?php echo $count_adults;?>&nbsp;</td>
        <td class="summary_cell"><?php echo $count_child_young;?>&nbsp;</td>
        <td class="summary_cell"><?php echo $count_child_older;?>&nbsp;</td>
        <td class="summary_cell"><?php echo $count_veg;?>&nbsp;</td>
        <td class="summary_cell"><?php echo $count_gf;?>&nbsp;</td>
        <td class="summary_cell"><?php echo $count_df;?></td>
      <?php 
          if ( $role == Utils::MEALS_ADMIN ) {
              echo '<td class="summary_cell">$' . number_format( $meal_income, 2 ) . '</td>';
          }
      ?>
      </tr>
    </table>
</div>
<p>
    <div>
        <?php 
          if ( $role == Utils::MEALS_ADMIN ) {
            echo '<form action="#" method="post">';
            echo '<input type="submit" name="download_attendees" value="Download Attendees"/>';
            echo '</form>';
          }
        ?>
    </div>
    <div>
        <?php 
          if ( $role == Utils::MEALS_ADMIN ) {
            echo '<form action="#" method="post">';
            echo '<input type="submit" name="email_attendees" value="Email Me Attendees"/>';
            echo '</form>';
          }
        ?>
    </div>
    <div>
        <?php $backLink = Utils::createLink('meal-list', array()); ?>
        <a href="<?php echo $backLink; ?>"><img src="img/action/back.png" alt="" title="Back to the list." class="icon"/></a>&nbsp;
        <a class="button" href="<?php echo $backLink; ?>">To the meal list</a>
    </div>
</p>